--
WEB_INTERFACE_ENABLED: true
WEB_INTERFACE_PORT: 9000
WEB_INTERFACE_HOST: "::"

UPLOAD_MODE_ENABLED: true
FILEBROWSER_BIN: "filebrowser -a [::] -r /iso -p 9001 --disable-exec --noauth"
FILEBROWSER_URL: "http://localhost:9001"